Repository dkanejs/docker-compose-maven-plugin, pull requests merged in 2019-09, with the labels that each got.

#70 Add github actions
  .github/workflows/ci-workflow.yml
  .travis.yml
Labels: CI

#67 added support for stop and restart commands
  README.md
  pom.xml
  src/it/restart/docker-compose.yml
  src/it/restart/pom.xml
  src/it/restart/verify.groovy
  src/it/stop/docker-compose.yml
  src/it/stop/pom.xml
  src/it/stop/verify.groovy
  src/main/java/com/dkanejs/maven/plugins/docker/compose/AbstractDockerComposeMojo.java
  src/main/java/com/dkanejs/maven/plugins/docker/compose/DockerComposeRestartMojo.java
  src/main/java/com/dkanejs/maven/plugins/docker/compose/DockerComposeStopMojo.java
Labels: enhancement, needs tests

#71 Making release 2.5.1
  README.md
  pom.xml
  src/it/pull-ignore-failures/docker-compose.yml
Labels: release
